version: "3.0"
services:
  postgresql:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: geomoz-server
      DATABASE_USERNAME: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5441:5432"